# Generated by Django 4.2 on 2023-04-23 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


INIT_DATA = {
    'Language': [
        {
            'name': "English",
            'priority': 5
        },
        {
            'name': "Spanish",
            'priority': 3
        },
        {
            'name': "French",
            'priority': 1
        },
        {
            'name': "Italian",
            'priority': 1
        },
        {
            'name': "Japanese",
            'priority': 1
        },
        {
            'name': "Dutch",
            'priority': 1
        },
        {
            'name': "Swedish",
            'priority': 1
        },
        {
            'name': "Norwegian",
            'priority': 1
        },
        {
            'name': "Finnish",
            'priority': 1
        },
        {
            'name': "Czech",
            'priority': 1
        }],
    'Category': [
        {
            'name': 'Beauty',
            'keywords': None
        },
        {
            'name': 'Travel',
            'keywords': None
        },
        {
            'name': 'Music',
            'keywords': None
        },
        {
            'name': 'Food',
            'keywords': None
        },
        {
            'name': 'Science',
            'keywords': None
        },
        {
            'name': 'Gaming',
            'keywords': None
        },
        {
            'name': 'Energy',
            'keywords': None
        },
        {
            'name': 'News',
            'keywords': None
        },
        {
            'name': 'Sports',
            'keywords': None
        },
        {
            'name': 'Tech',
            'keywords': None
        },
        {
            'name': 'World',
            'keywords': None
        },
        {
            'name': 'Finance',
            'keywords': None
        },
        {
            'name': 'Politics',
            'keywords': None
        },
        {
            'name': 'Business',
            'keywords': None
        },
        {
            'name': 'Economics',
            'keywords': None
        },
        {
            'name': 'Entertainment',
            'keywords': None
        },
    ]
}


def create_initial_data(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    for model_name in INIT_DATA:
        for model_data in INIT_DATA[model_name]:
            Type = apps.get_model("core", model_name)
            Type.objects.using(db_alias).create(**model_data)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('keywords', models.CharField(default=None, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=10000)),
                ('params', models.JSONField()),
                ('shown_times', models.IntegerField(default=0)),
                ('chat_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('language', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.language')),
            ],
        ),
        migrations.RunPython(create_initial_data),
    ]
