# Generated by Django 4.2 on 2023-08-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_name",
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
