# Generated by Django 4.2 on 2023-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='object_words',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='category',
            name='subject_words',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
